export default {
  // Light
  ppfd: "PPFD",

  // Energy equivalents
  adp: "ADP",
  atp: "ATP",
  atp_tot: "AP_tot",
  nadp: "NADP",
  nadph: "NADPH",
  nadp_tot: "NADP_tot",

  // Phosphates
  pi: "Pi",
  pi_tot: "Pi_tot",

  // Gases
  co2: "CO2",
  co2_intercellular: "Ci",
  o2: "O2",
  h2o2: "H2O2",

  // Protons / pH
  ph: "pH",
  ph_lumen: "pH_lumen",
  protons: "protons",
  protons_lumen: "protons_lumen",

  // CBB cycle
  rubp: "RUBP",
  ru5p: "RU5P",
  pga: "PGA",
  bpga: "BPGA",
  dhap: "DHAP",
  gap: "GAP",
  s7p: "S7P",
  e4p: "E4P",

  // Physical constants
  gas_constant: "R",
  faraday_constant: "F",
  temperature: "T",

  // Photosynthetic electron transport
  pq: "PQ",
  pqh2: "PQH2",
  pq_tot: "PQ_tot",
  pc_ox: "PC_ox",
  pc_red: "PC_red",
  pc_tot: "PC_tot",
  fd_ox: "Fd_ox",
  fd_red: "Fd_red",
  fd_tot: "Fd_tot",
  qa: "QA",
  qa_red: "QA_red",
  qa_tot: "QA_total",
  p700_tot: "P700_total",
  hpr: "HPR",
  b_h: "bH",

  // Photosystem antenna & regulatory pools
  psii_tot: "PSII_total",
  psi_tot: "PSI_total",
  lhc_tot: "LHC_tot",
  psbs_tot: "PsbS_tot",
  b0: "B0",
  b1: "B1",
  b2: "B2",
  b3: "B3",
  a1: "A1",

  // Fluorescence & regulation outputs
  npq_coefficient: "Q",
  npq: "NPQ",
  fluorescence: "Fluo",

  // PSII photochemistry / quenching rate constants
  psii_rate_constant: "k2",
  npq_heat_dissipation_rate: "kH",
  base_heat_dissipation_rate: "kH0",
  fluorescence_rate_constant: "kF",

  // Xanthophyll cycle
  zeaxanthin_fraction: "zx",
  violaxanthin_fraction: "vx",

  // Redox midpoint potentials
  e0_qa: "E0_QA",
  e0_pq: "E0_PQ",
  e0_pc: "E0_PC",
  e0_p700: "E0_P700",
  e0_nadp: "E0_NADP",
  e0_fd: "E0_Fd",
  e0_fa: "E0_FA",
  e0_fnr: "E0_fnr",

  // Photosystem / electron-transport-chain reactions
  r_atp_synthase: "ATP synthase",
  r_proton_leak: "proton leak",
  r_fnr: "FNR",
  r_b6f: "cyt b6f",
  r_ndh: "NDH",
  r_ptox: "PTOX",
  r_psii: "PSII",
  r_psi: "PSI",
  r_cyclic_electron_flow: "cyclic electron flow",
  r_lhc_state_transition_12: "LHC state transition 1->2",
  r_lhc_state_transition_21: "LHC state transition 2->1",
  r_pq_reduction: "PQ reduction",

  // Antenna & pigment pool parameters
  static_antenna_i: "staticAntI",
  static_antenna_ii: "staticAntII",
  carotenoids_tot: "Carotenoids_tot",
  psii_cross_section: "PSII_cross_section",
  n_st: "n_ST",
  pi_mol: "Pi_mol",

  // Rate / equilibrium constants for specific electron-transport steps
  k_stt7: "kStt7",
  k_ptox: "kPTOX",
  k_pq_red: "kPQred",
  k_pph1: "kPph1",
  k_pc_ox: "kPCox",
  k_fd_red: "kFdred",
  kf_proton_leak: "kf_proton_leak",
  kf_ndh: "kf_ndh",
  kf_cyclic_electron_flow: "kf_cyclic_electron_flow",
  kf_atp_synthase: "kf_atp_synthase",
  km_lhc_state_transition_12: "km_lhc_state_transition_12",
  km_fnr_nadp: "km_fnr_NADP",
  kcat_fnr: "kcat_fnr",
  kcat_b6f: "kcat_b6f",
  k_zsat: "K_ZSat",
  keq_atp_synthase: "keq_atp_synthase",
  keq_b6f: "keq_b6f",
  keq_fnr: "keq_fnr",
  keq_ferredoxin_reductase: "keq_ferredoxin_reductase",
  keq_pc_p700: "keq_PCP700",
  vmax_fnr: "vmax_fnr",

  // NPQ regulatory coefficients
  gamma0: "gamma0",
  gamma1: "gamma1",
  gamma2: "gamma2",
  gamma3: "gamma3",

  // Thermodynamics
  delta_g0_atp: "DeltaG0_ATP",
  delta_g_ph: "dG_pH",
  rt: "RT",

  // CBB cycle sugar phosphates (matuszynska2019 / poolman2000 / saadat2021)
  f6p: "F6P",
  g6p: "G6P",
  g1p: "G1P",
  fbp: "FBP",
  sbp: "SBP",
  x5p: "X5P",
  r5p: "R5P",

  // CBB cycle reactions
  r_rubisco_carboxylase: "rubisco carboxylase",
  r_phosphoglycerate_kinase: "phosphoglycerate kinase",
  r_gadph: "GAPDH",
  r_triose_phosphate_isomerase: "triose phosphate isomerase",
  r_aldolase_dhap_gap: "aldolase (DHAP+GAP)",
  r_aldolase_dhap_e4p: "aldolase (DHAP+E4P)",
  r_fbpase: "FBPase",
  r_transketolase_gap_f6p: "transketolase (GAP+F6P)",
  r_transketolase_gap_s7p: "transketolase (GAP+S7P)",
  r_sbpase: "SBPase",
  r_ribose_phosphate_isomerase: "ribose phosphate isomerase",
  r_ribulose_phosphate_epimerase: "ribulose phosphate epimerase",
  r_phosphoribulokinase: "phosphoribulokinase",
  r_g6pi: "G6P isomerase",
  r_phosphoglucomutase: "phosphoglucomutase",
  r_ex_g1p: "G1P export",

  // CBB cycle enzyme kinetics
  kcat_rubisco_carboxylase: "kcat_rubisco_carboxylase",
  km_rubisco_carboxylase_rubp: "km_rubisco_carboxylase_RUBP",
  km_rubisco_carboxylase_co2: "km_rubisco_carboxylase_CO2",
  ki_rubisco_carboxylase_pga: "ki_rubisco_carboxylase_3PGA",
  ki_rubisco_carboxylase_fbp: "ki_rubisco_carboxylase_FBP",
  ki_rubisco_carboxylase_sbp: "ki_rubisco_carboxylase_SBP",
  ki_rubisco_carboxylase_nadph: "ki_rubisco_carboxylase_NADPH",
  kre_phosphoglycerate_kinase: "kre_phosphoglycerate_kinase",
  keq_phosphoglycerate_kinase: "keq_phosphoglycerate_kinase",
  kre_gadph: "kre_gadph",
  keq_gadph: "keq_gadph",
  kre_triose_phosphate_isomerase: "kre_triose_phosphate_isomerase",
  keq_triose_phosphate_isomerase: "keq_triose_phosphate_isomerase",
  kre_aldolase_dhap_gap: "kre_aldolase_dhap_gap",
  keq_aldolase_dhap_gap: "keq_aldolase_dhap_gap",
  kre_aldolase_dhap_e4p: "kre_aldolase_dhap_e4p",
  keq_aldolase_dhap_e4p: "keq_aldolase_dhap_e4p",
  e0_fbpase: "E0_fbpase",
  kcat_fbpase: "kcat_fbpase",
  km_fbpase_s: "km_fbpase_s",
  ki_fbpase_f6p: "ki_fbpase_F6P",
  kre_transketolase_gap_f6p: "kre_transketolase_gap_f6p",
  keq_transketolase_gap_f6p: "keq_transketolase_gap_f6p",
  kre_transketolase_gap_s7p: "kre_transketolase_gap_s7p",
  keq_transketolase_gap_s7p: "keq_transketolase_gap_s7p",
  e0_sbpase: "E0_SBPase",
  kcat_sbpase: "kcat_SBPase",
  km_sbpase_s: "km_SBPase_s",
  kre_ribose_phosphate_isomerase: "kre_ribose_phosphate_isomerase",
  keq_ribose_phosphate_isomerase: "keq_ribose_phosphate_isomerase",
  kre_ribulose_phosphate_epimerase: "kre_ribulose_phosphate_epimerase",
  keq_ribulose_phosphate_epimerase: "keq_ribulose_phosphate_epimerase",
  e0_phosphoribulokinase: "E0_phosphoribulokinase",
  kcat_phosphoribulokinase: "kcat_phosphoribulokinase",
  km_phosphoribulokinase_ru5p: "km_phosphoribulokinase_RU5P",
  km_phosphoribulokinase_atp: "km_phosphoribulokinase_ATP",
  ki_phosphoribulokinase_pga: "ki_phosphoribulokinase_3PGA",
  ki_phosphoribulokinase_rubp: "ki_phosphoribulokinase_RUBP",
  kre_g6pi: "kre_g6pi",
  keq_g6pi: "keq_g6pi",
  kre_phosphoglucomutase: "kre_phosphoglucomutase",
  keq_phosphoglucomutase: "keq_phosphoglucomutase",
  e0_ex_g1p: "E0_ex_g1p",
  km_ex_g1p_g1p: "km_ex_g1p_G1P",
  km_ex_g1p_atp: "km_ex_g1p_ATP",
  ki_ex_g1p: "ki_ex_g1p",
  ki_ex_g1p_pga: "ki_ex_g1p_3PGA",
  ki_ex_g1p_f6p: "ki_ex_g1p_F6P",
  ki_ex_g1p_fbp: "ki_ex_g1p_FBP",
  kcat_ex_g1p: "kcat_ex_g1p",
  vmax_rubisco_carboxylase: "vmax_rubisco_carboxylase",
  vmax_fbpase: "vmax_fbpase",
  vmax_sbpase: "vmax_SBPase",
  vmax_phosphoribulokinase: "vmax_phosphoribulokinase",
  vmax_ex_g1p: "vmax_ex_g1p",
  ki_rubisco_carboxylase_pi: "ki_rubisco_carboxylase_Pi",
  ki_fbpase_pi: "ki_fbpase_Pi",
  ki_sbpase_pi: "ki_SBPase_Pi",
  ki_phosphoribulokinase_pi: "ki_phosphoribulokinase_Pi",
  r_glycine_decarboxylase: "glycine decarboxylase",
  k_recomb: "k_recomb",
  phi_triplet: "phi_triplet",
  phi_1o2: "phi_1O2",
  sigma0_ii: "sigma0_II",
  c_b6f: "c_b6f",
  pka_reg: "pKa_reg",
  em_pc_ph7: "Em_PC_pH7",
  em_pqh2_ph7: "Em_PQH2_pH7",
  vmax_b6f: "Vmax_b6f",
  pka_psbs: "pKa_PsbS",
  npq_max: "NPQ_max",
  k_qa: "k_QA",
  keq_qa: "Keq_QA",
  k_pctop700: "k_PCtoP700",
  k_fdtonadp: "k_FdtoNADP",
  k_st: "K_st",
  k_kea3: "k_KEA3",
  p_k: "P_K",
  vmax_atpsynth: "Vmax_ATPsynth",
  k_ez: "k_EZ",
  nh_vde: "nh_VDE",
  pka_vde: "pKa_VDE",
  vmax_vde: "Vmax_VDE",
  dpsi: "Dpsi",
  k_lu: "K_lu",
  single_oxygen: "singO2",
  psbsp: "PsbSP",
  phipsii: "PhiPSII",
  pmf: "pmf",
  delta_ph: "delta_pH",
  delta_ph_involts: "delta_pH_inVolts",
  r_psii_recomb: "vPSII_recomb",
  r_psii_charge_separation: "vPSII_ChSep",
  r_psi_charge_separation: "PSI_ChSep",
  r_psi_pc_oxidation: "v_PSI_PCoxid",
  r_cbb: "v_CBB",
  r_kea3: "v_KEA3",
  r_vkc: "v_VKC",
  r_epoxidation: "v_Epox",
  r_deepoxidation: "v_Deepox",
  h_stroma: "H_stroma",
  k_cbb: "k_CBB",
  net_assimilation_rate: "A",
  psbs_deepoxidized: "psbs_de",
  psbs_protonated: "psbs_pr",
  r_lhc_protonation: "LHC protonation",
  r_lhc_deprotonation: "LHC deprotonation",
  r_violaxanthin_deepoxidase: "violaxanthin deepoxidase",
  r_zeaxanthin_epoxidase: "zeaxanthin epoxidase",
  kf_lhc_protonation: "kf_lhc_protonation",
  kh_lhc_protonation: "kh_lhc_protonation",
  ksat_lhc_protonation: "ksat_lhc_protonation",
  kf_lhc_deprotonation: "kf_lhc_deprotonation",
  kf_violaxanthin_deepoxidase: "kf_violaxanthin_deepoxidase",
  kh_violaxanthin_deepoxidase: "kh_violaxanthin_deepoxidase",
  ksat_violaxanthin_deepoxidase: "ksat_violaxanthin_deepoxidase",
  kf_zeaxanthin_epoxidase: "kf_zeaxanthin_epoxidase",
  n_translocator: "N_translocator",
  kcat_n_translocator: "kcat_N_translocator",
  e0_n_translocator: "E0_N_translocator",
  r_ex_pga: "PGA export",
  r_ex_gap: "GAP export",
  r_ex_dhap: "DHAP export",
  km_ex_pga: "km_ex_pga",
  km_ex_gap: "km_ex_gap",
  km_ex_dhap: "km_ex_dhap",
  vmax_ex_pga: "vmax_ex_pga",
  ki_phosphoribulokinase_4: "ki_phosphoribulokinase_4",
  ki_phosphoribulokinase_5: "ki_phosphoribulokinase_5",
};
